## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Gartenbau Z.M."
theme = "hugo-story"


## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "public"

# Remote
#baseURL = "https://caressofsteel.github.io/demos/hugo/hugo-story/"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-E5KYW0WG7E"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]
# marinovic-garten-hausmeisterservice@gmx.de